"use strict";
const inversify_1 = require('inversify');
const docker_image_management_impl_1 = require('./implementations/docker-image-management-impl');
const docker_ode_impl_1 = require("./implementations/util/docker-ode-impl");
const docker_util_impl_1 = require("./implementations/util/docker-util-impl");
const docker_container_management_impl_1 = require("./implementations/docker-container-management-impl");
const firmament_yargs_1 = require('firmament-yargs');
const docker_command_impl_1 = require("./implementations/commands/docker-command-impl");
const make_command_impl_1 = require("./implementations/commands/make-command-impl");
const docker_management_impl_1 = require("./implementations/docker-management-impl");
var dockerKernel = new inversify_1.Container();
dockerKernel.bind('DockerManagement').to(docker_management_impl_1.DockerManagementImpl);
dockerKernel.bind('DockerImageManagement').to(docker_image_management_impl_1.DockerImageManagementImpl);
dockerKernel.bind('DockerContainerManagement').to(docker_container_management_impl_1.DockerContainerManagementImpl);
dockerKernel.bind('DockerOde').to(docker_ode_impl_1.DockerOdeImpl);
dockerKernel.bind('DockerUtil').to(docker_util_impl_1.DockerUtilImpl);
dockerKernel.bind('Command').to(docker_command_impl_1.DockerCommandImpl);
dockerKernel.bind('Command').to(make_command_impl_1.MakeCommandImpl);
let kernel = inversify_1.Container.merge(dockerKernel, firmament_yargs_1.kernel);
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = kernel;
//# sourceMappingURL=inversify.config.js.map