import { Command, CommandLine, CommandUtil, Spawn } from 'firmament-yargs';
import { DockerImageManagement } from "../interfaces/docker-image-management";
import { DockerContainerManagement } from "../interfaces/docker-container-management";
export declare class DockerCommandImpl implements Command {
    aliases: string[];
    command: string;
    commandDesc: string;
    handler: (argv: any) => void;
    options: any;
    subCommands: Command[];
    private commandUtil;
    private dockerImageManagement;
    private dockerContainerManagement;
    private commandLine;
    private spawn;
    constructor(_commandUtil: CommandUtil, _spawn: Spawn, _dockerImageManagement: DockerImageManagement, _dockerContainerManagement: DockerContainerManagement, _commandLine: CommandLine);
    private buildCommandTree();
    private pushCleanVolumesCommand();
    private pushRemoveImagesCommand();
    private pushRemoveContainersCommand();
    private pushShellCommand();
    private pushStartCommand();
    private pushStopCommand();
    private pushImagesCommand();
    private pushPsCommand();
    private printImagesList(argv, cb);
    private printContainerList(argv, cb);
    private bashInToContainer(ids, cb);
    private prettyPrintDockerImagesList(err, images, cb);
    private prettyPrintDockerContainerList(err, containers, all, cb);
}
