version: "3.3"

networks:
  default:
    external:
      name: merlin_net
services:
  #HDFS and Spark Name Node Service
  elasticsearch:
    image: 52.0.211.45:5000/elasticsearch:5.6.6
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    command: "elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch -Ediscovery.zen.minimum_master_nodes=1"
  elasticsearch-head:
    image: 52.0.211.45:5000/elasticsearch-head:5.x
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    ports:
      - "9100:9100"

