version: "3.3"
networks:
  net:
services:
  postgres:
    image: 52.0.211.45:5000/postgres:9.5.10
    environment:
      - POSTGRES_PASSWORD=password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5432:5432"
    networks:
      - net
  amino3:
    image: 52.0.211.45:5000/amino3:latest
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "3000:3000"
    networks:
      - net

