version: "3.2"
networks:
  net:
volumes:
  flibber:
    driver: local
    driver_opts:
      type: cifs
      device: //10.1.70.252/merlin
      options: "username=jreeme,password:&UJM4rfv"
services:
  stagingserver:
      image: 10.1.70.193:5000/merlin-hadoop-base
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure
      volumes:
        - flibber:/share
      networks:
        - net
      command: "/root/hadoop_entrypoint.sh"
