import {kernel} from 'firmament-bash';
import {Command} from 'firmament-yargs';
import {DockerImageManagement} from './interfaces/docker-image-management';
import {DockerImageManagementImpl} from './implementations/docker-image-management-impl';
import {DockerOde} from './interfaces/dockerode';
import {DockerOdeImpl} from './implementations/util/docker-ode-impl';
import {DockerUtil} from './interfaces/docker-util';
import {DockerUtilImpl} from './implementations/util/docker-util-impl';
import {DockerContainerManagement} from './interfaces/docker-container-management';
import {DockerContainerManagementImpl} from './implementations/docker-container-management-impl';
import {DockerCommandImpl} from './implementations/commands/docker-command-impl';
import {MakeCommandImpl} from './implementations/commands/make-command-impl';
import {DockerManagement} from './interfaces/docker-management';
import {DockerManagementImpl} from './implementations/docker-management-impl';
import {DockerMakeImpl} from './implementations/docker-make-impl';
import {DockerMake} from './interfaces/docker-make';
import {ProvisionCommandImpl} from './implementations/commands/provision-command-impl';
import {DockerProvision} from './interfaces/docker-provision';
import {DockerProvisionImpl} from './implementations/docker-provision-impl';

kernel.bind<DockerManagement>('DockerManagement').to(DockerManagementImpl);
kernel.bind<DockerMake>('DockerMake').to(DockerMakeImpl);
kernel.bind<DockerProvision>('DockerProvision').to(DockerProvisionImpl);
kernel.bind<DockerImageManagement>('DockerImageManagement').to(DockerImageManagementImpl);
kernel.bind<DockerContainerManagement>('DockerContainerManagement').to(DockerContainerManagementImpl);
kernel.bind<DockerOde>('DockerOde').to(DockerOdeImpl);
kernel.bind<DockerUtil>('DockerUtil').to(DockerUtilImpl);
kernel.bind<Command>('Command').to(DockerCommandImpl);
kernel.bind<Command>('Command').to(MakeCommandImpl);
kernel.bind<Command>('Command').to(ProvisionCommandImpl);

export default kernel;
